-- Affiliate Program (Phase 1: Attribution Core) Tables for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS affiliates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wp_customer_id TEXT UNIQUE NOT NULL,
  referral_code TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- pending | approved | rejected | suspended
  commission_rate NUMERIC NOT NULL DEFAULT 0.10, -- 0.10 / 0.12 / 0.15
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_id BIGINT NOT NULL REFERENCES affiliates(id),
  landing_path TEXT NOT NULL,
  user_agent TEXT,
  ip_address TEXT,
  clicked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS affiliate_conversions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_id BIGINT NOT NULL REFERENCES affiliates(id),
  wc_order_id BIGINT NOT NULL,
  order_total NUMERIC NOT NULL,
  commission_rate_applied NUMERIC NOT NULL,
  commission_amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- pending | approved | paid | voided
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_conversions ENABLE ROW LEVEL SECURITY;

-- Server-side (service role) access only in Phase 1 — no public/anon
-- policies yet, since there is no public UI reading or writing these
-- tables until Phase 2. The service role key used by API routes bypasses
-- RLS, so no policy is required for this phase's own code to function;
-- these tables simply have no public access surface at all right now.

CREATE INDEX IF NOT EXISTS idx_affiliates_referral_code ON affiliates (referral_code);
CREATE INDEX IF NOT EXISTS idx_affiliates_wp_customer_id ON affiliates (wp_customer_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate_id ON affiliate_clicks (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_affiliate_id ON affiliate_conversions (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_wc_order_id ON affiliate_conversions (wc_order_id);
