-- Artist Applications Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS artist_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT NOT NULL,
  portfolio_url TEXT,
  medium TEXT NOT NULL,
  sample_urls TEXT[],
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE artist_applications ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for artist applications" ON artist_applications
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON artist_applications
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create an index for faster lookups
CREATE INDEX IF NOT EXISTS idx_artist_applications_email ON artist_applications (email);