-- Canvas Roll Enquiries Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS canvas_roll_enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  company_name TEXT,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  product_interest TEXT NOT NULL,
  material_preference TEXT,
  quantity TEXT,
  message TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE canvas_roll_enquiries ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for canvas roll enquiries" ON canvas_roll_enquiries
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON canvas_roll_enquiries
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create an index for faster lookups
CREATE INDEX IF NOT EXISTS idx_canvas_roll_enquiries_email ON canvas_roll_enquiries (email);
