-- Custom Portrait Requests Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS custom_portrait_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wc_order_id BIGINT,
  wc_order_number TEXT,
  portrait_type TEXT NOT NULL,
  width_inches NUMERIC NOT NULL,
  height_inches NUMERIC NOT NULL,
  estimated_price NUMERIC NOT NULL,
  deposit_amount NUMERIC NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  reference_images TEXT,
  notes TEXT,
  payment_status TEXT DEFAULT 'pending',
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE custom_portrait_requests ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for custom portrait requests" ON custom_portrait_requests
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON custom_portrait_requests
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_custom_portrait_requests_wc_order_id ON custom_portrait_requests (wc_order_id);
CREATE INDEX IF NOT EXISTS idx_custom_portrait_requests_email ON custom_portrait_requests (email);
