-- Custom Orders Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS custom_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT,
  concept TEXT NOT NULL,
  size TEXT,
  colors TEXT,
  reference_images TEXT,
  rooms TEXT,
  number_of_paintings INTEGER DEFAULT 1,
  budget_range TEXT,
  categories TEXT,
  additional_notes TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE custom_orders ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
-- Adjust as needed
CREATE POLICY "Allow insert for custom orders" ON custom_orders
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON custom_orders
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create an index on order_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_custom_orders_order_id ON custom_orders (order_id);
CREATE INDEX IF NOT EXISTS idx_custom_orders_email ON custom_orders (email);
