-- Design Partner Applications Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS design_partner_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  studio_name TEXT,
  city TEXT NOT NULL,
  project_type TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  mood_board_url TEXT,
  message TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE design_partner_applications ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for design partner applications" ON design_partner_applications
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON design_partner_applications
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create an index for faster lookups
CREATE INDEX IF NOT EXISTS idx_design_partner_applications_email ON design_partner_applications (email);
