-- Gift cards — run this in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS gift_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  original_amount NUMERIC NOT NULL,
  remaining_balance NUMERIC NOT NULL,
  purchaser_email TEXT NOT NULL,
  wc_order_id BIGINT,
  status TEXT NOT NULL DEFAULT 'active', -- 'active' | 'depleted'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS gift_cards_code_idx ON gift_cards (code);

CREATE TABLE IF NOT EXISTS gift_card_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gift_card_id BIGINT NOT NULL REFERENCES gift_cards(id),
  wc_order_id BIGINT NOT NULL,
  amount_redeemed NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE gift_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_card_redemptions ENABLE ROW LEVEL SECURITY;
