-- Photography Offers Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS photography_offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id TEXT UNIQUE NOT NULL,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_slug TEXT,
  offer_amount NUMERIC NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  postcode TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'IN',
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE photography_offers ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for photography offers" ON photography_offers
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON photography_offers
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_photography_offers_offer_id ON photography_offers (offer_id);
CREATE INDEX IF NOT EXISTS idx_photography_offers_email ON photography_offers (email);
CREATE INDEX IF NOT EXISTS idx_photography_offers_product_id ON photography_offers (product_id);
