-- Promotion Popup Leads Table for Artace Studio
-- Captures email + phone from the site-wide offer popup (components/ui/PromotionModal.tsx)
-- before the coupon code is revealed.
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS promotion_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  coupon_code TEXT NOT NULL,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE promotion_leads ENABLE ROW LEVEL SECURITY;

-- Allow insert from anon (for the popup's API route, called with the service role key)
CREATE POLICY "Allow insert for promotion leads" ON promotion_leads
  FOR INSERT
  WITH CHECK (true);

-- Allow select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON promotion_leads
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Index for de-duping / lookups by email
CREATE INDEX IF NOT EXISTS idx_promotion_leads_email ON promotion_leads (email);
