-- Artace Rewards (loyalty program) ledger — run this in the Supabase SQL editor.
-- One row per point-affecting event; balance is always SUM(points), never
-- stored redundantly, so it can't drift out of sync.

CREATE TABLE IF NOT EXISTS rewards_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wp_customer_id TEXT NOT NULL,
  wc_order_id BIGINT,
  points INTEGER NOT NULL,
  type TEXT NOT NULL, -- 'earn' | 'redeem' | 'clawback'
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS rewards_ledger_customer_idx ON rewards_ledger (wp_customer_id);
CREATE INDEX IF NOT EXISTS rewards_ledger_order_idx ON rewards_ledger (wc_order_id);

ALTER TABLE rewards_ledger ENABLE ROW LEVEL SECURITY;
