-- Samora "early access" newsletter signups — separate from any Artace-wide
-- mailing list, scoped to Samora's own growth/restock-notification use case
-- (matches its own "small batches, nothing rushed" narrative).
CREATE TABLE IF NOT EXISTS samora_newsletter_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  source_page TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS samora_newsletter_signups_email_idx ON samora_newsletter_signups (email);

ALTER TABLE samora_newsletter_signups ENABLE ROW LEVEL SECURITY;

-- Server-side (service role) access only — matches every other lead-capture
-- table in this project (corporate_leads, trade_applications, etc.). No
-- public/anon policies needed since the API route (using the service role
-- key) is the only writer and there is no public read UI.
