-- Trade Applications Table for Artace Studio
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS trade_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  company_name TEXT,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  profession TEXT NOT NULL,
  portfolio_url TEXT,
  message TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (recommended)
ALTER TABLE trade_applications ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows insert from anon (for your API)
CREATE POLICY "Allow insert for trade applications" ON trade_applications
  FOR INSERT
  WITH CHECK (true);

-- Create a policy that allows select for authenticated users (admin)
CREATE POLICY "Allow select for authenticated users" ON trade_applications
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_trade_applications_email ON trade_applications (email);
